version: '3'

services:
  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
      # depends_on:
      # - wordpress
    ports:
      - "443:443"
        # networks:
        #   - inception
    volumes:
      - ./nginx/conf/:/etc/nginx/http.d/
      - /etc/nginx/ssl:/etc/nginx/ssl/
      - /var/www/public/html:/var/www/public/html
        #- wp-volume:/var/www/
        # env_file:
        #- .env
    restart: always
